// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

const (
	UserStatusOk       = 0 // 用户状态正常
	UserStatusDisabled = 1 // 用户状态禁用
	UserGenderUnknown  = 0 // 性别: 未知
	UserGenderMale     = 1 // 性别: 男
	UserGenderFemale   = 2 // 性别: 女
)


// 用户注册
type UserRegisterReq struct {
	UserRegisterInput
	Passport string `v:"required#请输入账号"`  // 账号
	Password string `v:"required#请输入密码"`  // 密码
	Nickname string `v:"required#请输入昵称"`  // 昵称
	Captcha  string `v:"required#请输入验证码"` // 验证码
}

// 创建用户
type UserRegisterInput struct {
	Passport string // 账号
	Password string // 密码(明文)
	Nickname string // 昵称
}

// 修改用户密码
type UserPasswordReq struct {
	UserPasswordInput
	OldPassword string `v:"required#请输入原始密码"` // 原密码
	NewPassword string `v:"required#请输入新密码"`  // 新密码
}

type UserPasswordInput struct {
	OldPassword string // 原密码
	NewPassword string // 新密码
}

// 修改用户
type UserUpdateProfileReq struct {
	UserUpdateProfileInput
	Nickname string `v:"required#请输入昵称信息"` // 昵称
}

// 禁用用户
type UserDisableReq struct {
	Id *uint `v:"required#请选择需要禁用的用户"` // 删除时ID不能为空
}

// Api用户登录
type UserLoginReq struct {
	UserLoginInput
	Passport string `v:"required#请输入账号"`  // 账号
	Password string `v:"required#请输入密码"`  // 密码(明文)
	Captcha  string `v:"required#请输入验证码"` // 验证码
}

// 用户登录
type UserLoginInput struct {
	Passport string // 账号
	Password string // 密码(明文)
}

// 用户信息
type UserGetProfileOutput struct {
	Id       uint           // 用户ID
	Nickname string         // 昵称
	Avatar   string         // 头像地址
	Gender   int            // 性别 0: 未设置 1: 男 2: 女
	Stats    map[string]int // 发布内容数量
}

// 修改用户头像
type UserUpdateAvatarInput struct {
	Avatar string // 头像地址
}

// 修改用户
type UserServiceUpdateProfileReq struct {
	Nickname string // 昵称
	Gender   int    // 性别 0: 未设置 1: 男 2: 女
}

// 修改用户信息
type UserUpdateProfileInput struct {
	Id       uint   // 用户ID
	Nickname string // 昵称
	Avatar   string // 头像地址
	Gender   int    // 性别 0: 未设置 1: 男 2: 女
}

// 查询用户列表请求
type UserGetListReq struct {
	UserGetListInput
	Id uint
}

// 查询用户列表输入
type UserGetListInput struct {
	ContentGetListInput
	Id uint
}

// 查询用户详情结果
type UserGetListOutput struct {
	Content *ContentGetListOutput `json:"content"` // 查询用户
	User    *UserGetProfileOutput `json:"user"`    // 查询用户
	Stats   map[string]int        // 发布内容数量
}

// 查询用户列表查询请求
type UserGetMessageListReq struct {
	UserGetMessageListInput
}

type UserGetMessageListInput struct {
	Page       int    `json:"page"`        // 分页码
	Size       int    `json:"size"`        // 分页数量
	TargetType string `json:"target_type"` // 数据类型
	TargetId   int    `json:"target_id"`   // 数据ID
	UserId     uint   `json:"user_id"`     // 用户ID
}

// 查询用户列表查询结果
type UserGetMessageListOutput struct {
	List  []ReplyGetListOutputItem `json:"list"`  // 列表
	Page  int                      `json:"page"`  // 分页码
	Size  int                      `json:"size"`  // 分页数量
	Total int                      `json:"total"` // 数据总数
	Stats map[string]int           // 发布内容数量
}
