// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"focus-single/internal/model"
)

type IFile interface {
	Upload(ctx context.Context, in model.FileUploadInput) (*model.FileUploadOutput, error)
}

var localFile IFile

func File() IFile {
	return localFile
}

func RegisterFile(i IFile) {
	localFile = i
}
