// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-17 21:12:32
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Setting is the golang structure for table setting.
type Setting struct {
	K         string      `json:"k"         description:"键名"`
	V         string      `json:"v"         description:"键值"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"更新时间"`
}
