// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// UserDao is the manager for logic model data accessing and custom defined data operations functions management.
type UserDao struct {
	gmvc.M             // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      userColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB      // DB is the raw underlying database management object.
	Table  string      // Table is the underlying table name of the DAO.
}

// UserColumns defines and stores column names for table gf_user.
type userColumns struct {
	Id        string // UID
	Passport  string // 账号
	Password  string // MD5密码
	Nickname  string // 昵称
	Avatar    string // 头像地址
	Status    string // 状态 0:启用 1:禁用
	Gender    string // 性别 0: 未设置 1: 男 2: 女
	CreatedAt string // 注册时间
	UpdatedAt string // 更新时间
}

// NewUserDao creates and returns a new DAO object for table data access.
func NewUserDao() *UserDao {
	columns := userColumns{
		Id:        "id",
		Passport:  "passport",
		Password:  "password",
		Nickname:  "nickname",
		Avatar:    "avatar",
		Status:    "status",
		Gender:    "gender",
		CreatedAt: "created_at",
		UpdatedAt: "updated_at",
	}
	return &UserDao{
		C:     columns,
		M:     g.DB("default").Model("gf_user").Safe(),
		DB:    g.DB("default"),
		Table: "gf_user",
	}
}
